// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostID        string                 `protobuf:"bytes,1,opt,name=HostID,proto3" json:"HostID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMetrics) Reset() {
	*x = HostMetrics{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMetrics) ProtoMessage() {}

func (x *HostMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMetrics.ProtoReflect.Descriptor instead.
func (*HostMetrics) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *HostMetrics) GetHostID() string {
	if x != nil {
		return x.HostID
	}
	return ""
}

type CPUMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usage         []float64              `protobuf:"fixed64,1,rep,packed,name=Usage,proto3" json:"Usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUMetrics) Reset() {
	*x = CPUMetrics{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUMetrics) ProtoMessage() {}

func (x *CPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUMetrics.ProtoReflect.Descriptor instead.
func (*CPUMetrics) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *CPUMetrics) GetUsage() []float64 {
	if x != nil {
		return x.Usage
	}
	return nil
}

type MemMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Total          uint64                 `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Free           uint64                 `protobuf:"varint,2,opt,name=Free,proto3" json:"Free,omitempty"`
	UsedPercentage float64                `protobuf:"fixed64,3,opt,name=UsedPercentage,proto3" json:"UsedPercentage,omitempty"`
	Available      uint64                 `protobuf:"varint,4,opt,name=Available,proto3" json:"Available,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemMetrics) Reset() {
	*x = MemMetrics{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemMetrics) ProtoMessage() {}

func (x *MemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemMetrics.ProtoReflect.Descriptor instead.
func (*MemMetrics) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *MemMetrics) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemMetrics) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *MemMetrics) GetUsedPercentage() float64 {
	if x != nil {
		return x.UsedPercentage
	}
	return 0
}

func (x *MemMetrics) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

type DiskMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Used          uint64                 `protobuf:"varint,2,opt,name=Used,proto3" json:"Used,omitempty"`
	Free          uint64                 `protobuf:"varint,3,opt,name=Free,proto3" json:"Free,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskMetrics) Reset() {
	*x = DiskMetrics{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetrics) ProtoMessage() {}

func (x *DiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetrics.ProtoReflect.Descriptor instead.
func (*DiskMetrics) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *DiskMetrics) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DiskMetrics) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *DiskMetrics) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

type ServiceMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	CPU           float64                `protobuf:"fixed64,3,opt,name=CPU,proto3" json:"CPU,omitempty"`
	Memory        float32                `protobuf:"fixed32,4,opt,name=Memory,proto3" json:"Memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceMetrics) Reset() {
	*x = ServiceMetrics{}
	mi := &file_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMetrics) ProtoMessage() {}

func (x *ServiceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMetrics.ProtoReflect.Descriptor instead.
func (*ServiceMetrics) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceMetrics) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceMetrics) GetCPU() float64 {
	if x != nil {
		return x.CPU
	}
	return 0
}

func (x *ServiceMetrics) GetMemory() float32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *HostMetrics           `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	CPU           *CPUMetrics            `protobuf:"bytes,2,opt,name=CPU,proto3" json:"CPU,omitempty"`
	Memory        *MemMetrics            `protobuf:"bytes,3,opt,name=Memory,proto3" json:"Memory,omitempty"`
	Disk          *DiskMetrics           `protobuf:"bytes,4,opt,name=Disk,proto3" json:"Disk,omitempty"`
	Services      []*ServiceMetrics      `protobuf:"bytes,5,rep,name=Services,proto3" json:"Services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *Metrics) GetHost() *HostMetrics {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Metrics) GetCPU() *CPUMetrics {
	if x != nil {
		return x.CPU
	}
	return nil
}

func (x *Metrics) GetMemory() *MemMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *Metrics) GetDisk() *DiskMetrics {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *Metrics) GetServices() []*ServiceMetrics {
	if x != nil {
		return x.Services
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\ametrics\"%\n" +
	"\vHostMetrics\x12\x16\n" +
	"\x06HostID\x18\x01 \x01(\tR\x06HostID\"\"\n" +
	"\n" +
	"CPUMetrics\x12\x14\n" +
	"\x05Usage\x18\x01 \x03(\x01R\x05Usage\"|\n" +
	"\n" +
	"MemMetrics\x12\x14\n" +
	"\x05Total\x18\x01 \x01(\x04R\x05Total\x12\x12\n" +
	"\x04Free\x18\x02 \x01(\x04R\x04Free\x12&\n" +
	"\x0eUsedPercentage\x18\x03 \x01(\x01R\x0eUsedPercentage\x12\x1c\n" +
	"\tAvailable\x18\x04 \x01(\x04R\tAvailable\"K\n" +
	"\vDiskMetrics\x12\x14\n" +
	"\x05Total\x18\x01 \x01(\x04R\x05Total\x12\x12\n" +
	"\x04Used\x18\x02 \x01(\x04R\x04Used\x12\x12\n" +
	"\x04Free\x18\x03 \x01(\x04R\x04Free\"f\n" +
	"\x0eServiceMetrics\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\tR\x06Status\x12\x10\n" +
	"\x03CPU\x18\x03 \x01(\x01R\x03CPU\x12\x16\n" +
	"\x06Memory\x18\x04 \x01(\x02R\x06Memory\"\xe6\x01\n" +
	"\aMetrics\x12(\n" +
	"\x04Host\x18\x01 \x01(\v2\x14.metrics.HostMetricsR\x04Host\x12%\n" +
	"\x03CPU\x18\x02 \x01(\v2\x13.metrics.CPUMetricsR\x03CPU\x12+\n" +
	"\x06Memory\x18\x03 \x01(\v2\x13.metrics.MemMetricsR\x06Memory\x12(\n" +
	"\x04Disk\x18\x04 \x01(\v2\x14.metrics.DiskMetricsR\x04Disk\x123\n" +
	"\bServices\x18\x05 \x03(\v2\x17.metrics.ServiceMetricsR\bServices\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2I\n" +
	"\rMetricService\x128\n" +
	"\rStreamMetrics\x12\x10.metrics.Metrics\x1a\x11.metrics.Response\"\x00(\x01B?Z=github.com/NaduniRabel/distributed-system-monitor/proto;protob\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_metrics_proto_goTypes = []any{
	(*HostMetrics)(nil),    // 0: metrics.HostMetrics
	(*CPUMetrics)(nil),     // 1: metrics.CPUMetrics
	(*MemMetrics)(nil),     // 2: metrics.MemMetrics
	(*DiskMetrics)(nil),    // 3: metrics.DiskMetrics
	(*ServiceMetrics)(nil), // 4: metrics.ServiceMetrics
	(*Metrics)(nil),        // 5: metrics.Metrics
	(*Response)(nil),       // 6: metrics.Response
}
var file_metrics_proto_depIdxs = []int32{
	0, // 0: metrics.Metrics.Host:type_name -> metrics.HostMetrics
	1, // 1: metrics.Metrics.CPU:type_name -> metrics.CPUMetrics
	2, // 2: metrics.Metrics.Memory:type_name -> metrics.MemMetrics
	3, // 3: metrics.Metrics.Disk:type_name -> metrics.DiskMetrics
	4, // 4: metrics.Metrics.Services:type_name -> metrics.ServiceMetrics
	5, // 5: metrics.MetricService.StreamMetrics:input_type -> metrics.Metrics
	6, // 6: metrics.MetricService.StreamMetrics:output_type -> metrics.Response
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
